spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vrpsolver
    username: vrpsolver
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
