spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

google:
  maps:
    api:
      enabled: true
      key: ${GOOGLE_MAPS_API_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
