name: VRP Solver CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Execute tests
        run: mvn -f vrp-solver-api/pom.xml clean test

  push_to_registry:
    if: github.event_name == 'push'

    needs: testing

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ vars.DOCKER_HUB_USER }}/${{ vars.DOCKER_HUB_REPOSITORY_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./vrp-solver-api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
